#!/bin/bash
echo Generating qspi cached image...
${0%/*}/../../../binaries/bin2image qspi_cached $2 $2".cached"
echo Programming qspi cached image...
${0%/*}/../../../binaries/cli_programmer $1 write_qspi 0x0 $2".cached"
